import pytest
from pipeline.images import (
    validate_visual_quality_policy,
    VisualQualityPolicyError,
)


def test_visual_policy_ai_generation_succeeds():
    # When all scenes are generated by real AI providers, policy passes
    manifest = {
        1: "huggingface",
        2: "huggingface",
        3: "pollinations",
        4: "deapi",
        5: "huggingface",
        6: "pollinations",
    }
    # Should not raise
    validate_visual_quality_policy(manifest, allow_procedural=False)


def test_visual_policy_blocks_procedural_when_disallowed():
    # If any scene used procedural fallback and allow_procedural is False, must raise
    manifest = {
        1: "huggingface",
        2: "procedural_pil_fallback",
        3: "procedural_pil_fallback",
        4: "huggingface",
        5: "procedural_pil_fallback",
        6: "procedural_pil_fallback",
    }
    with pytest.raises(VisualQualityPolicyError) as exc_info:
        validate_visual_quality_policy(manifest, allow_procedural=False)

    err = str(exc_info.value)
    assert "Visual Quality Policy Violation" in err
    assert "procedural placeholders" in err.lower()
    assert "2" in err or "3" in err


def test_visual_policy_allows_procedural_when_explicitly_permitted():
    # If allow_procedural is True, policy passes even with procedural fallback
    manifest = {
        1: "procedural_pil_fallback",
        2: "procedural_pil_fallback",
        3: "procedural_pil_fallback",
        4: "procedural_pil_fallback",
        5: "procedural_pil_fallback",
        6: "procedural_pil_fallback",
    }
    # Should not raise when explicitly allowed
    validate_visual_quality_policy(manifest, allow_procedural=True)
